### ISSUE TITLE
Legacy D2 Saves

### ISSUE THREAD

**Issue by TR1337** [ferib/D2R-Offline#63] opened 2021-04-18 21:42 UTC
On attempting to load legacy D2 saves I'm presented with the error: 
"Unable to enter game.  Bad character quest data"
Attempting to load through hosting TCP/IP presents me with the same error yet again

Running ver2.0.4 with the default patch:
0xD4AD68:9090
0xD4E25F:909090909090
0xCAFB9D:90B001
0x597E1C:90909090909090
0xC5E81C:9090C346455242: ~ MP stack corruption bypass
0xD615F2:909090909090909090909090909090909090909090909090909090: ~ show all calsses on load (shalzuth)
0x39FC03:9090909090909090909090909090909090909090: ~ allow chars to load (shalzuth)

**Comment by ferib** [comment] 2021-04-18 21:43
Duplicate of #7, fix using `-FixLocalSave` using `v2.0.5`.

**Closed by ferib** 2021-04-18 21:43 UTC

**Comment by TR1337** [comment] 2021-04-19 01:18
![Capture](https://user-images.githubusercontent.com/82781711/115168251-83c4b500-a0ba-11eb-9efc-ff5314c9f073.PNG)

**Comment by TR1337** [comment] 2021-04-19 01:19
Tried looking it up, couldn't figure out why it's doing that

**Comment by mfrklic** [comment] 2021-04-19 02:27
Are you running the following at the command line?
D2ROffline.exe -FixLocalSave

**Comment by TR1337** [comment] 2021-04-19 02:50
Yeah, made a shortcut and ran the -FixLocalSave command line, got the error in the attached image.

**Comment by mfrklic** [comment] 2021-04-19 04:16
Ah your trying to load legacy saves? Not sure if ALL classic legacy saves are fully compatible yet with the Alpha. This fix is to fix local play for games created with the Alpha.

**Comment by csuhta** [comment] 2021-04-19 04:21
As far as I know, only very simple 1.07 saves created with Hero Editor can be imported right now. Like an empty character and maybe a few valid items at most. Other saves don’t import with the current version of the Alpha
