### ISSUE TITLE
a3-a5 patch not working in 2.0.7

### ISSUE THREAD

**Issue by djgrubic** [ferib/D2R-Offline#94] opened 2021-04-21 16:59 UTC
I'm not entirely sure how that's supposed to work, but I've completed act 2 and Meshif still only returns me to the main menu.

**Comment by ferib** [comment] 2021-04-22 00:35
https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#how-do-i-go-to-act-iii-iv-or-v

Possible duplicate of #104.

**Closed** 2021-04-22 00:40 UTC
