### ISSUE TITLE
Fail to start single player but TCP/IP host success

### ISSUE THREAD

**Issue by penut85420** [ferib/D2R-Offline#25] opened 2021-04-17 00:37 UTC
This is strange, but it still playable. And i notice that i can choose other class earlier, but now i can only choose three class. The language patch worked at first time, but after restarting it came back to english.

**Comment by ferib** [comment] 2021-04-17 00:39
Partly duplicate of #7 
Language patches are very time-critical as explained in #24 and will most likely fail (for now)

**Closed by ferib** 2021-04-17 00:39 UTC
