### ISSUE TITLE
Can't resume the game with an existing character

### ISSUE THREAD

**Issue by DEV7163** [ferib/D2R-Offline#17] opened 2021-04-16 14:07 UTC
As title, when I try to play with the lvl 8 barbarian I created yesterday it shows the loading screen for a second and then returns me back to the character selection.

Thanks!

**Comment by mfrklic** [comment] 2021-04-16 14:22
Duplicate of #7 
https://github.com/ferib/D2R-Offline/issues/7

Quick and easy fix is to use TCP/IP option to host. If you do not see the TCP/IP option -- make a copy of game.exe in D2R folder as game2.exe and use D2ROffline to run the new exe. If you continue to have missing TCP/IP issue you may need to keep renaming game2.exe to something new until a long term fix is done.

The only drawback of using TCP/IP is shared stash will not work. If you want to "fix" your save to play local only you need to use the D2RSaveFix source provided in the other thread to compile and load your game to force it to think you finished normal mode in your save.

**Comment by DEV7163** [comment] 2021-04-16 14:26
Thanks! And sorry, I found it was duplicated as soon as I posted, my bad I didn't check.

**Closed** 2021-04-16 19:22 UTC
