### ISSUE TITLE
Sometimes patch will fail

### ISSUE THREAD

**Issue by CaiMiao** [ferib/D2R-Offline#27] opened 2021-04-17 03:38 UTC
![image](https://user-images.githubusercontent.com/4640483/115100746-95eb0a00-9f79-11eb-9b8e-d09b4834508d.png)

I doubt new patch timing is not that stable. IIRC same thing will happen D2Modding so I switched here...

**Comment by ferib** [comment] 2021-04-17 03:40
This is not related to the patch timing, this is duplicate of #2

**Closed** 2021-04-17 03:41 UTC
